// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-toolkit.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var TOOLKIT = [
  {
    id: "dealforge",
    name: "DealForge",
    tagline: "Find profitable deals in seconds",
    price: "$29/mo",
    description: "Chrome extension that analyzes any rental arbitrage deal using Derek's proprietary scoring algorithm. Instant profit projections, market risk scoring, and comp data while browsing Zillow, Apartments.com, or Craigslist."
  },
  {
    id: "foundry",
    name: "The Foundry",
    tagline: "Launch units 10x faster",
    price: "$197 one-time",
    description: "AI website builder that generates a direct booking site in minutes. Includes Stripe payments, guest CRM, SEO pages, and business setup templates (LLC, operating agreement, banking)."
  },
  {
    id: "negotiator",
    name: "The Negotiator",
    tagline: "AI cold calls landlords for you",
    price: "$97/mo + $0.50/call",
    description: "Upload a landlord list; AI runs voice + SMS outreach, schedules tours, and generates counter-offers from Derek's 240-unit playbook. Follow-up automation until you get a response."
  },
  {
    id: "jarvis",
    name: "Jarvis",
    tagline: "Your AI operating partner",
    price: "Included in full toolkit",
    description: "Always-on agent that monitors your STR business. Learns your expense allocation, tracks per-unit P&L, monitors reviews, and automates guest communication with anomaly detection."
  }
];
var get_toolkit_default = defineTool({
  name: "get_toolkit",
  title: "Get AI toolkit",
  description: "Return the four AI tools STR Forge offers to support portfolio owners (DealForge, The Foundry, The Negotiator, Jarvis) with pricing and descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TOOLKIT, null, 2) }],
    structuredContent: { tools: TOOLKIT }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var PRICING = {
  software: {
    name: "Software (DIY)",
    description: "Self-serve access to STR Forge's AI toolkit for portfolio owners who want to run pieces themselves.",
    tiers: [
      { name: "DealForge", price: "$29/mo", includes: "Deal analysis Chrome extension + pipeline" },
      { name: "The Foundry", price: "$197 one-time", includes: "AI direct-booking site builder + business setup templates" },
      { name: "The Negotiator", price: "$97/mo + $0.50/call", includes: "AI landlord outreach, tour scheduling, negotiation" },
      { name: "Full Toolkit", price: "$297/mo", includes: "All tools bundled + Jarvis AI operating partner" }
    ]
  },
  services: {
    name: "Services (Done-With-You)",
    description: "Hands-on execution partnership with Derek Cheung's team \u2014 sourcing, management, and buildout across arbitrage and purchase deals.",
    tiers: [
      { name: "Launch Sprint", price: "Contact for quote", includes: "We help you launch your first units end-to-end" },
      { name: "Scale Partner", price: "Contact for quote", includes: "Ongoing hands-on operations for 10-50 unit portfolios" }
    ]
  }
};
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get pricing",
  description: "Return STR Forge pricing across the Software (DIY) and Services (Done-With-You) tiers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PRICING, null, 2) }],
    structuredContent: PRICING
  })
});

// src/lib/mcp/tools/get-founder.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var FOUNDER = {
  name: "Derek Cheung",
  role: "Founder, STR Forge",
  background: "Built and operated a 240-unit Airbnb portfolio combining arbitrage and purchase deals. STR Forge productizes his sourcing, negotiation, management, and buildout playbooks so investors and busy professionals can forge their own portfolio without assembling the machine from scratch.",
  positioning: "STR Forge is a founder-led Airbnb portfolio platform \u2014 arbitrage deals for cash flow and scale, purchase deals for equity and tax savings, with management and buildout handled end to end.",
  audience: "Investors and busy professionals who want a real Airbnb portfolio without operating it day to day."
};
var get_founder_default = defineTool3({
  name: "get_founder_info",
  title: "Get founder info",
  description: "Return background on STR Forge founder Derek Cheung and how the product is positioned.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FOUNDER, null, 2) }],
    structuredContent: FOUNDER
  })
});

// src/lib/mcp/tools/get-resources-overview.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var OVERVIEW = {
  name: "Client Resource Vault",
  access: "Password-protected. Existing clients have the password; this tool only describes what's inside.",
  contents: [
    "Landlord outreach scripts and negotiation frameworks from Derek's 240-unit playbook",
    "LLC formation, banking, and credit-strategy templates",
    "Direct-booking site templates and SEO checklists",
    "Guest communication templates and review-response playbooks",
    "Per-unit P&L spreadsheets and expense-allocation guides"
  ],
  url: "https://www.thestrforge.com/resources"
};
var get_resources_overview_default = defineTool4({
  name: "get_resources_overview",
  title: "Get resource vault overview",
  description: "Describe what lives in the STR Forge client Resource Vault (does not expose the password or protected files).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(OVERVIEW, null, 2) }],
    structuredContent: OVERVIEW
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "str-forge-mcp",
  title: "STR Forge",
  version: "0.1.0",
  instructions: "Public read-only tools for STR Forge, a founder-led Airbnb portfolio platform founded by Derek Cheung. STR Forge is a one-stop shop for investors and busy professionals who want to forge a real Airbnb portfolio. The flow is Find BNB \u2192 Build BNB \u2192 Manage BNB \u2192 Scale BNB: arbitrage deals for scale, purchase deals for equity and tax savings, with buildout and management handled end to end. Use these tools to answer questions about the flywheel, pricing, the founder, and the client Resource Vault.",
  tools: [get_toolkit_default, get_pricing_default, get_founder_default, get_resources_overview_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
